let token = localStorage.getItem('token')||null;let me={username:null,friends:[]};const d=(s)=>document.querySelector(s);
function api(path,method='GET',body=null){return fetch(path,{method,headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},credentials:'include',body:body?JSON.stringify(body):null}).then(r=>r.json());}
function addMsg(m){const el=document.createElement('div');el.className='msg'+(m.from===me.username?' you':'');el.innerHTML=`<div class="meta"><b>${m.from||'system'}</b> • ${new Date(m.ts||Date.now()).toLocaleTimeString()}</div><div>${m.text}</div>`;d('#messages').appendChild(el);d('#messages').scrollTop=d('#messages').scrollHeight;}
function addSystem(t){const el=document.createElement('div');el.className='msg';el.textContent=t;d('#messages').appendChild(el);}
function renderRooms(obj){const ul=d('#roomList');ul.innerHTML='';for(const [name,count] of Object.entries(obj||{})){const li=document.createElement('li');li.innerHTML=`<span>${name}</span><span>${count}</span>`;li.onclick=()=>socket.emit('joinRoom',name);ul.appendChild(li);}}
function renderFriends(){const ul=d('#friendList');ul.innerHTML='';for(const f of me.friends||[]){const li=document.createElement('li');li.textContent=f;li.onclick=()=>{const t=prompt('DM to '+f); if(t) socket.emit('dm',{to:f,text:t});};ul.appendChild(li);}}
d('#sendOtpBtn').onclick=async ()=>{const email=d('#loginEmail').value.trim(); if(!email) return alert('email'); const r=await api('/api/auth/request-otp','POST',{email}); if(!r.ok) return alert(r.error||'err'); d('#otpArea').style.display='block'; d('#loginHint').textContent=r.sent?'Check email':'OTP logged to server';}
d('#verifyOtpBtn').onclick=async ()=>{const email=d('#loginEmail').value.trim();const code=d('#otpCode').value.trim();const r=await api('/api/auth/verify-otp','POST',{email,code}); if(!r.ok) return alert(r.error||'err'); token=r.token; localStorage.setItem('token',token); if(!r.user.username){d('#profileModal').style.display='flex';} else await afterLogin(); d('#loginModal').style.display='none';}
d('#saveProfileBtn').onclick=async ()=>{const username=d('#username').value.trim();const gender=d('#gender').value;const bio=d('#bio').value.trim();const avatar=d('#avatar').value.trim();const r=await api('/api/profile','POST',{username,gender,bio,avatar}); if(!r.ok) return alert(r.error||'err'); me=r.user; d('#meName').textContent=me.username; d('#avatarPreview').src=me.avatar||`https://ui-avatars.com/api/?name=${encodeURIComponent(me.username)}`; d('#profileModal').style.display='none'; await afterLogin();}
d('#createRoomBtn').onclick=async ()=>{const name=d('#newRoomName').value.trim(); if(!name) return alert('enter name'); const r=await api('/api/rooms/create','POST',{name}); if(!r.ok) return alert(r.error||'err'); d('#newRoomName').value=''; if(socket) socket.emit('joinRoom', r.name);}
d('#addFriendBtn').onclick=async ()=>{const name=d('#friendName').value.trim(); if(!name) return; const r=await api('/api/friends/add','POST',{username:name}); if(!r.ok) return alert(r.error||'err'); if(!me.friends.includes(name)) me.friends.push(name); renderFriends(); alert(r.mutual? 'Mutual!':'Request sent'); d('#friendName').value='';}
let socket=null;
async function afterLogin(){const r=await api('/api/me'); if(!r.ok) return; me=r.user; d('#meName').textContent=me.username||'Guest'; d('#avatarPreview').src=me.avatar||`https://ui-avatars.com/api/?name=${encodeURIComponent(me.username||'U')}`; socket=io({ auth:{ token } }); socket.on('ready',({rooms})=>{const obj={}; rooms.forEach(r=>obj[r.name]=r.count); renderRooms(obj); d('#msgInput').disabled=false; d('#sendBtn').disabled=false;}); socket.on('roomCounts',renderRooms); socket.on('memberCount',({room,count})=>{d('#roomName').textContent=room; d('#memberCount').textContent=count;}); socket.on('system',m=>addSystem(m.text)); socket.on('message',m=>addMsg(m)); socket.on('errorMsg',m=>addSystem('⚠ '+m)); d('#sendBtn').onclick=()=>{const v=d('#msgInput').value.trim(); if(!v) return; socket.emit('message', v); d('#msgInput').value='';}; d('#msgInput').addEventListener('keydown',e=>{ if(e.key==='Enter') d('#sendBtn').click(); }); renderFriends();}
window.addEventListener('load',async ()=>{ if(token){ try{ await afterLogin(); d('#loginModal').style.display='none'; }catch(e){ d('#loginModal').style.display='flex'; } } else d('#loginModal').style.display='flex'; });